<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHN5eQ2G\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHN5eQ2G/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHN5eQ2G.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHN5eQ2G\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHN5eQ2G\App_KernelDevDebugContainer([
    'container.build_hash' => 'HN5eQ2G',
    'container.build_id' => 'a494ccb0',
    'container.build_time' => 1621284257,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHN5eQ2G');
